defaults: &defaults
  host: localhost
  database: restaurtr_local

development:
  <<: *defaults

test:
  <<: *defaults
  database: restaurtr_test

production:
  <<: *defaults
  host: flame.mongohq.com
  port: 27060
  username: derek
  password: test123
  database: restaurtr


