defaults: &defaults
  host: flame.mongohq.com
  port: 27060
  username: derek
  password: test123
  database: restaurtr

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
#  host: <%= ENV['MONGO_HOST'] %>
#  port: <%= ENV['MONGO_PORT'] %>
#  username: <%= ENV['MONGO_USER'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
#  database: <%= ENV['MONGO_DATABASE'] %>
