defaults: &defaults
  host: localhost
  database: restaurtr_test

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: flame.mongohq.com
  port: 27060
  username: derek
  password: test123
  database: restaurtr


